orion-rs/orion

src/hkdf.rs, src/hmac.rs
(the old comments might have mislead people into thinking 10-byte keys are safe)
=> Fix doc-comments to use 16-bytes keys instead of 10-byte keys

src/hazardous/pbkdf2.rs, src/lib.rs
Fixes #30. The fix has the same approach as the one used by [ring](https://github.com/briansmith/ring/blob/7e3682c02170f5eafa423b63bacfa018de2878a9/src/pbkdf2.rs#L161) and is also used in the `chacha20` module.
=> Fix PBKDF2 length check

src/hazardous/cshake.rs
If the value of a variable is based on a condition it is more idiomatic
to use let x = if { a } else { b }; Plus more readable too.
=> More idiomatic value assignment

Cargo.toml
As far as I can tell, the `ConstantTimeEq` trait is only used internally, and is not implemented on any public types, so this should be a semver-compatible change that does not require incrementing the major version.
=> Use subtle v2

Cargo.toml, src/errors/mod.rs, src/lib.rs, src/util/mod.rs
This avoids having unneeded dependencies that `rand` automatically imports.
=> Switch from rand to rand_os

.travis.yml, Cargo.toml, src/hazardous/aead/chacha20poly1305.rs, src/hazardous/hash/blake2b.rs, src/hazardous/hash/sha512.rs, src/hazardous/kdf/hkdf.rs, src/hazardous/kdf/pbkdf2.rs, src/hazardous/mac/hmac.rs, src/hazardous/mac/poly1305.rs, src/hazardous/stream/chacha20.rs, src/util/mod.rs
Fixes #50.
This removes all `inline` attributes from public API's. Nearly all other `inline` attributes have been made `#[inline]` to not have the compiler make inline expansion every time, as with `#[inline(always)]`. Some internal functions still use `#[inline(always)]`, but only because benchmarks showed a significant regression when changed to `#[inline]`.
This improves compilation time and in some cases also performance.
`travis-ci.yml` has also been updated to test in both `src` and `tests` with ASan again.
=> Remove inline attributes from public API's

src/hazardous/mac/hmac.rs
This refactors the HMAC implementation. Usage of `mem::swap` is not longer needed, due to not using the `sha2` crate any longer. The streaming `Hmac` state is also changed to hold processed `Sha512` states of `ipad` and `opad` which cuts down operations in especially `reset()` and also `finalize()`. The `Hmac` state no longer needs a `Drop` impl, as this is handled by the `Sha512` states. 
Speed comparisons with cargo-benchcmp report a speed increase of ~x1.5 for PBKDF2.
=> Refactor HMAC and increase performance for PBKDF by ~x1.5

Cargo.toml, src/hazardous/hash/blake2b.rs, src/hazardous/hash/sha512.rs, src/hazardous/mac/hmac.rs, src/hazardous/mac/poly1305.rs, src/hazardous/stream/chacha20.rs, src/kdf.rs, src/lib.rs, src/pwhash.rs, src/typedefs.rs
This will avoid needing a C compiler on stable Rust, since zeroize has no build-dependencies.
=> Switch form clear_on_drop to zeroize

src/aead.rs, src/auth.rs, src/hash.rs, src/hazardous/aead/chacha20poly1305.rs, src/hazardous/aead/xchacha20poly1305.rs, src/hazardous/hash/blake2b.rs, src/hazardous/hash/sha512.rs, src/hazardous/kdf/hkdf.rs, src/hazardous/kdf/pbkdf2.rs, src/hazardous/mac/hmac.rs, src/hazardous/mac/poly1305.rs, src/hazardous/stream/chacha20.rs, src/hazardous/stream/xchacha20.rs, src/hazardous/xof/cshake.rs, src/kdf.rs, src/lib.rs, src/pwhash.rs, src/util/mod.rs
=> Rephrase "Exceptions" to "Errors" and add orion::hash to root docs

src/hazardous/aead/chacha20poly1305.rs, src/hazardous/aead/xchacha20poly1305.rs, src/hazardous/stream/chacha20.rs, src/hazardous/stream/xchacha20.rs
Currently ChaCha20 doesn't allow `plaintext` input parameters above `u32::max_value()` but the RFC defines the input restriction on a secret key/nonce combination as 2^32 blocks, meaning 2^32 * 64 bytes worth of data ([RFC section 2.3](https://tools.ietf.org/html/rfc8439#section-2.3)). 
This adds an internal counter to the internal ChaCha20 state, to check for the size restriction of 2^32 - 1 * 64 and panics if it is violated.
This size restriction also applies to XChaCha20, ChaCha20Poly1305 and XChaCha20Poly1305.
=> Correct size-limitation on input bytes to ChaCha20

src/typedefs.rs, src/util/mod.rs
This should avoid potential short-circuits. Using `unwrap_u8` was completely useless here.
=> Use subtle From<Choice> for bool impl instead of using unwrap_u8

.travis.yml
This organizes the build jobs with name attributes and specifies both `release` and `debug` tests for all jobs.
=> Clean up Travis CI build jobs

src/hazardous/hash/blake2b.rs, src/hazardous/hash/sha512.rs, src/hazardous/stream/chacha20.rs
Only allocate a `keystream_block` if the `ciphertext_block` is not long enough to hold the entire serialized keystream. This also merges the previous `round` function into `quarter_round` and removes some unneeded mutable `self` references in context structs of both Sha512, ChaCha20 and Blake2b.
Benchmarks report a ~30% performance increase in ChaCha20/XChaCha20 and ~20% in ChaCha20Poly1305/XChaCha20Poly1305.
=> Reduce memory footprint

src/typedefs.rs
This PR implements `PartialEq<&[u8]>` for all newtypes in constant-time. This is to avoid situations where users would compare against another slice(`==`) while calling the newtype's `unprotected_as_bytes()` function. This could happen in situations where users want to avoid creating a new instance of a newtype just to be able to compare with the currently provided `PartialEq` implementation.
TODO:
- [DONE [here](https://github.com/brycx/orion-fuzz/tree/pteq-slice), should be merged with this PR] Add tests in orion-fuzz
- [DONE [here](https://github.com/brycx/orion-dudect/tree/pteq-slice), should be merged with this PR] Add tests in orion-dudect
- [See #77] Add short example in docs of relevant newtypes and a accompanying security note
=> Implement PartialEq<&[u8]> for newtypes

src/typedefs.rs
One unresolved issue is having independent documentation generated for each type that a single macro creates. I'm not currently sure how to solve this.
=> Document newtype PartialEq usage 

src/endianness.rs
=> endianness: Remove tmp allocations and use TryFrom instead.

src/auth.rs, src/endianness.rs, src/hash.rs, src/hazardous/aead/chacha20poly1305.rs, src/hazardous/aead/xchacha20poly1305.rs, src/hazardous/hash/blake2b.rs, src/hazardous/hash/sha512.rs, src/hazardous/kdf/hkdf.rs, src/hazardous/mac/hmac.rs, src/hazardous/mac/poly1305.rs, src/hazardous/stream/chacha20.rs, src/hazardous/stream/xchacha20.rs
This changes the internal ChaCha20 implementation to resemble a SIMD vectorization. The `encrypt`/`decrypt` functions now also make use of in-place xoring with the keystream internally.
=> Vectorize ChaCha20

CHANGELOG.md, CONTRIBUTING.md, README.md
Adds contributing guidelines and makes the changelog more portable than it is using the GitHub API.
=> Add CONTRIBUTING guidelines and CHANGELOG

src/util/mod.rs
=> Remove redundant length check in secure_cmp

src/aead.rs, src/auth.rs, src/hash.rs, src/hazardous/aead/chacha20poly1305.rs, src/hazardous/aead/xchacha20poly1305.rs, src/hazardous/hash/blake2b.rs, src/hazardous/hash/sha512.rs, src/hazardous/kdf/hkdf.rs, src/hazardous/kdf/pbkdf2.rs, src/hazardous/mac/hmac.rs, src/hazardous/mac/poly1305.rs, src/hazardous/stream/chacha20.rs, src/hazardous/stream/xchacha20.rs, src/kdf.rs, src/pwhash.rs, src/typedefs.rs, src/util/mod.rs
+ Remove redundant must_use from internal fns
=> Address #90: Add must_use message to pub Results

benches/bench.rs, src/auth.rs, src/hazardous/aead/streaming.rs, src/hazardous/hash/blake2b.rs, src/hazardous/hash/sha512.rs, src/hazardous/mac/hmac.rs, src/hazardous/mac/poly1305.rs, src/kdf.rs, src/typedefs.rs, tests/hash/mod.rs, tests/mac/mod.rs
=> Public API changes to increase familiarity

.travis.yml, Cargo.toml, README.md, appveyor.yml
`subtle` has [added optimization barriers](https://github.com/dalek-cryptography/subtle/blob/master/CHANGELOG.md#221) on stable Rust, in version `2.2.1`. The reason we had a `nightly` feature before was to take advantage of these barriers, that were only available on nightly at the time.
This PR removes both `no_std` and `nightly` features in orion, making the crate-feature story a lot more simple. This enables using orion with `no_std` on both stable and nightly Rust (nightly is required for `no_std` now), only needing to specify `orion = { version = "*", default-features = false }`.
=> Remove "no_std" + "nightly" features and support no_std on stable

src/hazardous/hash/blake2b.rs, src/util/endianness.rs, src/util/mod.rs, src/util/u64x4.rs
This changes the internal BLAKE2b permutation to resemble SIMD vectorization (similar to how ChaCha20 [was vectorized](https://github.com/brycx/orion/pull/84)).
The approach to this vectorization has been taken from the [`blake2-rfc`](https://github.com/cesarb/blake2-rfc) crate.
This has shown the following increases in performance (measured on a Intel Core i7-4790K 4.0 GHz):
```
BLAKE2b-512/compute hash/512                                                                             
time:   [609.79 ns 610.74 ns 611.70 ns]
thrpt:  [798.24 MiB/s 799.50 MiB/s 800.73 MiB/s]
change:
time:   [-5.4893% -4.5062% -3.1013%] (p = 0.00 < 0.05)
thrpt:  [+3.2005% +4.7188% +5.8082%]
Performance has improved.
Found 11 outliers among 100 measurements (11.00%)
3 (3.00%) low mild
2 (2.00%) high mild
6 …
```
=> Vectorize BLAKE2b

src/aead.rs, src/hazardous/aead/streaming.rs
Closes #103 and closes #94 
There is one link in the documentation that i can not get to work, i have marked it with a TODO.
I'm a bit unsure if it is better to have a get_nonce method or if it is better to return Self and the Nonce in the `new` method.
Tests a rather minimal for now, but i think this should be fine since its only a thin wrapper around the hazardous API
Is it useful to expose the option to authenticate additional data? The "normal" AEAD seal function does not do it
=> Add high-level secret-stream API

src/errors/mod.rs
Implementing `std::error::Error` allows for better interoperability with error-handling crates and enables `UnknownCryptoError` to be used as the `source` for other errors. We also derive `Copy + Clone`.
=> Implement std::error::Error for UnknownCryptoError

src/aead.rs, src/hazardous/aead/chacha20poly1305.rs, src/hazardous/aead/streaming.rs, src/hazardous/aead/xchacha20poly1305.rs, src/hazardous/mac/poly1305.rs, src/hazardous/stream/chacha20.rs, src/hazardous/stream/xchacha20.rs, src/pwhash.rs
- Remove public `keystream_block` function. The same result can be achieved with all-0 input.
- Make `hazardous::aead::streaming::TAG_SIZE` constant public.
- Use a shared ChaCha20 state for encryption and authentication in `hazardous::aead`
- Have `hazardous::aead` return `Err()` if converting `usize` to `u64` would be a lossy conversion on the machine.
=> aead: Use shared ChaCha20 state and remove keystream_block

.github/workflows/test.yml, Cargo.toml, README.md, appveyor.yml, src/hazardous/kdf/argon2i.rs, src/hazardous/kdf/mod.rs, src/hazardous/stream/xchacha20.rs, src/lib.rs, src/util/endianness.rs
This enables using Argon2i in a `no_std` context, through the `alloc` crate. This is feature-gated with a "alloc" feature, to continue having heap allocations be opt-in.
Fixes #125.
=> Add no_std support for Argon2i with alloc

src/hazardous/aead/chacha20poly1305.rs, src/hazardous/aead/streaming.rs, src/hazardous/aead/xchacha20poly1305.rs, src/test_framework/aead_interface.rs, tests/aead/mod.rs
This change allows empty input on AEADs sealing operation. The authentication tag is still calculated, using the optional AAD and is copied to the out parameters.
TODO:
=> Allow empty input when sealing with AEADs in hazardous

src/hazardous/hash/sha512.rs
Fixes #140 
changed broken link to mbedTLS github official source code.
=> Update link to mbedTLS in sha512.

Cargo.toml, tests/aead/boringssl_tests.rs, tests/aead/mod.rs, tests/aead/other_xchacha20_poly1305.rs, tests/aead/pynacl_streaming_aead.rs, tests/aead/rfc_chacha20_poly1305.rs, tests/aead/wycheproof_aead.rs, tests/hash/blake2b_kat.rs, tests/hash/mod.rs, tests/hash/other_blake2b.rs, tests/kdf/custom_hkdf.rs, tests/kdf/custom_pbkdf2.rs, tests/kdf/mod.rs, tests/kdf/other_argon2i.rs, tests/kdf/other_hkdf.rs, tests/kdf/pynacl_argon2i.rs, tests/kdf/ref_argon2i.rs, tests/kdf/wycheproof_hkdf.rs, tests/mac/mod.rs, tests/mac/other_poly1305.rs, tests/mac/rfc_hmac.rs, tests/mac/wycheproof_hmac_sha512.rs, tests/mod.rs, tests/stream/mod.rs, tests/stream/rfc_chacha20.rs, tests/stream/rfc_xchacha20.rs
This is an additional to #129.
Using type-based de-/serialization significantly cleans the code and rids us of unearthly amounts of `unwrap()`s.
=> Typed de-/serialization for JSON-based tests

.github/workflows/test.yml, README.md, src/hazardous/aead/streaming.rs, src/hazardous/hash/blake2b.rs, src/hazardous/hash/sha512.rs, src/hazardous/kdf/argon2i.rs, src/hazardous/stream/chacha20.rs, src/high_level/auth.rs, src/high_level/hltypes.rs, src/high_level/kdf.rs, src/high_level/pwhash.rs, src/test_framework/streamcipher_interface.rs, src/typedefs.rs
=> Replace T::max_value() with MAX (#156)

src/high_level/pwhash.rs
The `pwhash::hash_password_verify` function is central to the UX of the
password verification portion of this library. Currently, it requires callers
to specify the iterations and memory to be used in the Argon2i hash that the
function performs.
However, one of the arguments to the function is a `PasswordHash` type. This
type represents a password that has already been hashed, and it contains the
memory and iterations that were used to hash it. It's almost certainly
a logical error to hash a password for the purpose of comparing it to another
hash generated using different parameters. We can save users from having to
specify the paramters---and eventually making a mistake doing so---by having
`hash_password_verify` just pull the parameters from the given `PasswordHash`.
We retain the …
=> Use encoded parameters in hash_password_verify

src/high_level/auth.rs
Closes #159 
@vlmutolo Does this change make sense, is it clear? I've extended upon your suggestion a bit, in order to make the comments align more the the use-case description/example in the top of the module docs.
> `orion::auth` can be used to ensure message integrity and authenticity by
using a secret key.
>
> An example of this could be securing APIs by having a user of a given API
sign their API request and having the API server verify these signed API
requests.
=> Doc: Change the example in orion::auth

.github/workflows/test.yml, deny.toml
Closes #146 
Adds `cargo-deny` to CI using their [recommended GH Actions pipeline](https://github.com/EmbarkStudios/cargo-deny-action#recommended-pipeline-to-avoid-sudden-breakages).
=> Add cargo-deny to CI

src/typedefs.rs
=> Limit high-level, variable-length newtype's input to isize::MAX

.github/workflows/lints.yml, .github/workflows/temp_nightly_tests.yml, src/hazardous/hash/sha2/mod.rs, src/hazardous/hash/sha2/sha256.rs, src/hazardous/hash/sha2/sha384.rs, src/hazardous/hash/sha2/sha512.rs, src/hazardous/kdf/hkdf.rs, src/hazardous/kdf/pbkdf2.rs, src/hazardous/mac/hmac.rs, src/util/endianness.rs
The recent support for SHA2 variants added the use of `min_const_generics`. The different implementations became largely duplicates and somewhat messy. 
With this change we put the largest amount of core-logic into a generic implementation of the SHA2 state, with different parameters instantiated for different variants. This should make it easier to verify and audit.
=> Cleanup of SHA2 implementations

benches/bench.rs
The benchmarks for SHA2 were added previously to `v016`.
=> Update benchmarks to include new SHA2 variants for SHA, HMAC, HKDF and PBKDF2

Cargo.toml, src/errors.rs, src/high_level/pwhash.rs
Replace the current Base64 dependency with one that provides constant-time encoding & decoding.
closes #188
=> Use constant-time Base64 in `pwhash::PasswordHash`

src/high_level/pwhash.rs
The PasswordHash docs were not updated to remove the warning about its base64 encoding and decoding operations being non-constant-time. Since the move to ct-codecs, they are now constant-time and the warning are no longer needed.
This should probably merge before v016.
=> remove erroneous non-constant-time warning

src/high_level/pwhash.rs, src/typedefs.rs
=> Add `is_empty()` to newtypes

src/high_level/aead.rs
closes #139 
#139 mentions the current example should be extended, but I felt like it grew so long it might actually have users turn away from it.
cc @vlmutolo, @snsmac
=> Documentation for correct use of streaming AEAD API with StreamTag::Finish

src/hazardous/ecc/x25519.rs, src/high_level/aead.rs, src/high_level/kex.rs, src/high_level/mod.rs, src/lib.rs
=> High-level API for key-exchange using X25519

Cargo.toml, src/high_level/aead.rs, src/high_level/auth.rs, src/high_level/hash.rs, src/high_level/kdf.rs, src/high_level/kex.rs, src/high_level/pwhash.rs, src/lib.rs
fixes #238 
`RUSTDOCFLAGS='--cfg docsrs' cargo +nightly doc --no-deps --all-features --open`
Screenshots:
=> Use `doc_cfg` to render feature badges for feature-gated functionality

src/hazardous/aead/streaming.rs, src/high_level/aead.rs, tests/aead/pynacl_streaming_aead.rs
This pr is related to issue #212.
Thanks to rust compiler, I changed function signature first then fix some errors caused by `cargo check`, `cargo clippy` and `cargo test`
=> Let seal_chunk take reference of StreamTag

.cargo/audit.toml, deny.toml
`serde_cbor` is used by `criterion` for benchmarking only, so we want to avoid failing builds due to this advisory only. Issue at `criterion` to switch to an alternative: https://github.com/bheisler/criterion.rs/issues/534
=> CI: Ignore `serde_cbor` unmaintained advisory

.github/workflows/test.yml, CONTRIBUTING.md, src/hazardous/aead/chacha20poly1305.rs, src/hazardous/aead/streaming.rs, src/hazardous/aead/xchacha20poly1305.rs, src/hazardous/ecc/x25519.rs, src/hazardous/kdf/argon2i.rs, src/hazardous/kdf/hkdf.rs, src/hazardous/kdf/pbkdf2.rs, src/hazardous/mac/blake2b.rs, src/hazardous/mac/hmac.rs, src/hazardous/mac/poly1305.rs, src/hazardous/stream/chacha20.rs, src/hazardous/stream/xchacha20.rs, src/typedefs.rs, src/util/mod.rs
closes #254 
Add feature-gating to doctests that make use of `safe-api` functionality. Additionally, remove `--tests` flag from `--no-default-features` builds in CI, in order to test that doctests run successfully on `no-std` builds.
=> Feature-gate doc examples to enable doctests on `--no-default-features` builds

src/hazardous/ecc/mod.rs
These are no longer needed, since we moved to the `fiat-crypto` crate and can be deleted.
=> x25519 (internal): Remove mod-level allows

.github/workflows/audit_check.yml
closes #251, #257
This adds the `audit-check` action to our workflow. This should create issues if vulnerable dependencies show up during the run, instead of just the current action failing and sending me an email. It should also fix #251.
We will keep the previous cargo audit check as well because, as mentioned in #257, it seems unclear how much support this `audit-check` action is receiving.
=> CI: Add `audit-check` to Actions workflow

src/hazardous/hash/blake2/blake2b.rs, src/hazardous/hash/sha2/sha256.rs, src/hazardous/hash/sha2/sha384.rs, src/hazardous/hash/sha2/sha512.rs, src/high_level/hash.rs
See #227.
---
EDIT: The scope of this PR has changed. We were going to try to fit the Read/Write impls for all of Orion's types into this PR, but then decided to split it up. #227 will keep track of all the impls.
Now this PR implements `std::io::Write` for Blake2b and adds a convenience function `orion::hash::digest_from_reader`.
=> impl standard IO traits for hashing

README.md, SECURITY.md, src/high_level/pwhash.rs, src/lib.rs, src/typedefs.rs, src/util/mod.rs, tests/aead/mod.rs, tests/mac/nist_cavp_hmac.rs
Also additional spelling corrections. I took care of the wiki a couple of days ago.
=> Capitalize crate name

deny.toml
=> Allow `Unicode-DFS-2016` license in dev-dependency tree

.github/workflows/audit_check.yml, .github/workflows/test.yml
`audit-check` has not seen any activity since 2020. We replace its functionality with `cargo-deny`.
Also bump `cargo-deny` action to `1.3.2`.
=> Remove unmaintained `audit-check` and replace with `cargo-deny`

src/hazardous/ecc/x25519.rs, src/hazardous/hash/blake2/blake2b.rs, src/hazardous/mac/blake2b.rs, src/high_level/pwhash.rs
Improve the docs for the `Blake2b::new()` function, by specifying that the `size` parameter is in bytes. Additionally, some clippy suggestions.
=> Improve `Blake2b::new()` docs

.github/workflows/test.yml
This adds a test of the benchmarks, to ensure they are up to date, in case the API changes. It doesn't run any actual benchmarks.
=> ci: Add benchmark check test without running any actual benchmarks

src/hazardous/aead/chacha20poly1305.rs, src/hazardous/aead/streaming.rs, src/hazardous/aead/xchacha20poly1305.rs, src/hazardous/stream/chacha20.rs, src/hazardous/stream/xchacha20.rs
=> (X)ChaCha20/(X)ChaCha20-Poly1305: Do not copy plaintext to `dst_out` before all needed keystream blocks are guaranteed to be produced

deny.toml
See rationale for this in #306
=> Ignore `RUSTSEC-2021-0145`

Cargo.toml, src/lib.rs
This is no longer recommended: https://github.com/rust-lang/api-guidelines/pull/230
=> Remove `html_root_url`

CHANGELOG.md, README.md, src/hazardous/kem/mod.rs, src/hazardous/kem/x25519_hkdf_sha256.rs, src/hazardous/mod.rs, tests/hpke/hpke_test_kats.rs, tests/hpke/mod.rs, tests/mod.rs
see #333 
Add support for the DHKEM(X25519, HKDF-SHA256) KEM from the HPKE RFC. Support for the HPKE functions Seal/Open can be added using this.
TODO:
- ~~[ ] Fuzzing targets~~: There seem to be no other crates available on crates.io that expose the DHKEM functionality that we do here. Those crates that have it internally are HPKE crates, and leave the KEM operations internal. The fuzzing targets will have to be added once full HPKE support has been added as well.
=> Add support for RFC 9180 KEM

CHANGELOG.md, Cargo.toml, src/hazardous/ecc/x25519.rs, src/hazardous/mac/poly1305.rs
The new release includes struct-based newtypes so this had to be adjusted for in Poly1305 and X25519.
Seems the `mips64-unknown-linux-gnuabi64` has somewhat been silently downgraded in target support with Rust `1.72` (https://github.com/rust-lang/rust/issues/115218). Maybe we can find a replacement?
=> Update `fiat-crypto` to `0.2.1`

.github/workflows/workflow_audit.yml
closes #438
https://woodruffw.github.io/zizmor/
TODO:
=> ci: Add `zizmor` workflow

tests/mac/other_poly1305.rs
Hi! I fixed a broken link to test vectors in `tests/mac/other_poly1305.rs`. The previous link pointed to an outdated location in the Monocypher repository.
=> chore: fixed dead link in `tests/mac/other_poly1305.rs`

.github/workflows/code_coverage.yml
Switch to using source-based coverage and `grcov` to measure code-coverage.
=> ci: Use source-based coverage

CHANGELOG.md, src/hazardous/kem/ml_kem/internal/mod.rs
With this we avoid re-computing for the hash for multiple `encap()` calls.
=> mlkem: Cache hash of encapsulation key

CHANGELOG.md, Cargo.toml, src/hazardous/ecc/x25519.rs, src/hazardous/kem/ml_kem/internal/mod.rs, src/hazardous/kem/ml_kem/mlkem1024.rs, src/hazardous/kem/ml_kem/mlkem512.rs, src/hazardous/kem/ml_kem/mlkem768.rs
With https://github.com/orion-rs/orion/commit/c5ea41841fd6c21549db3ad0d7d86aa0f6c881b0 we introduced caching the encapsulation key for a decapsulation key, to avoid recomputing it during `decap()`. That commit introduced an internal copy of `EncapKey` for `DecapKey`, which effectively meant the API that was user-accessible would end up storing an encapsulation key twice in memory, including the matrix.
This PR moves up the caching to the individual `DecapsulationKey` newtypes, to avoid this, and passes those cached values down to internal decapsulation logic instead.
=> `mlkem`: Move caching of encapsulation key

src/hazardous/hash/sha3/mod.rs, src/hazardous/kem/ml_kem/internal/mod.rs, src/high_level/kex.rs
**Description:**
This pull request addresses several typographical errors in the documentation comments across multiple files. The changes include:
1. **File:** `src/hazardous/hash/sha3/mod.rs`
- Corrected the spelling of "multiple" in a comment.
2. **File:** `src/hazardous/kem/ml_kem/internal/mod.rs`
- Fixed the spelling of "actually" in comments for encapsulation and decapsulation key checks.
3. **File:** `src/high_level/kex.rs`
- Corrected the spelling of "compatibility" in a comment related to test generation.
These changes improve the readability and professionalism of the codebase documentation. No functional code changes have been made.
=> Fix Typos in Documentation Comments

src/hazardous/kem/ml_kem/internal/mod.rs, src/test_framework/hpke_interface.rs
**Description:** 
This pull request corrects typographical errors in comments within the codebase. Specifically, it changes "withink" to "within" in `mod.rs` and corrects the capitalization in `hpke_interface.rs`. These changes improve the readability and professionalism of the code comments.
=> Fix Typographical Errors in Comments

src/hazardous/ecc/x25519.rs
This introduces a unit test for handling edge cases related to private keys in the x25519 algorithm. The test checks several edge cases for private keys, ensuring the implementation correctly handles these unusual but valid cases.
Test Scenarios Added:
- All Zeros: A private key with all zero values, which is clamped in RFC 7748, should be accepted.
- All Ones: A private key with all ones, which is clamped, should be accepted.
- Alternating Bits: A private key with an alternating bit pattern, which is an arbitrary pattern, should be accepted.
- First Byte Set: A private key where only the first byte is set, should be accepted.
- Last Byte Set: A private key where only the last byte is set, should be accepted.
=> Added unit test for edge cases on x25519 keys

.github/workflows/test.yml, Cargo.toml, README.md, src/hazardous/kdf/argon2i.rs, src/lib.rs, src/typedefs.rs
This fixes compilation that didn't succeed before like this: 
```sh
cargo b --features serde,alloc --no-default-features
```
And by auto-enabling `alloc` with serde it now works also like this:
```sh
cargo b --features serde --no-default-features
```
And it keeps working as before, like this:
```sh
cargo b
cargo b --features serde
cargo b --no-default-features
```
=> make `alloc` and `serde` compilation more robust

benches/bench.rs
Hey team! Found and fixed error in `benches/bench.rs`
`therefor` - `therefore` x2
=> fix spelling errors bench.rs

src/hazardous/kdf/mod.rs, src/hazardous/kdf/scrypt.rs
Adds a rust implementation of scrypt from RFC 7914. It requires the alloc feature right now, but could probably be updated to work without it.
I'm happy to hear any feedback, or make changes as required.
=> Add scrypt implementation #433

CONTRIBUTING.md
Replaced the outdated link to the Rust API Guidelines checklist (rust-lang-nursery.github.io) with the current official URL (rust-lang.github.io) in CONTRIBUTING.md. This ensures contributors are directed to the latest and correct guidelines for Rust API best practices. No other content was changed.
=> Update Rust API Guidelines link to current official URL

src/hazardous/kdf/argon2i.rs, tests/cae/mod.rs
Spotted and fixed a few wording hiccups:
`Therefor` - `Therefore`
=> polishing docs: error fixes for clarity

src/test_framework/kem_interface.rs
Corrected a misspelling in the keygen_encap_decap_roundtrip test function name within kem_interface.rs (rountrip → roundtrip) to improve code clarity and consistency.
=> Fix typo in KEM test function name
