orion-rs/orion

- README.md
- src/default.rs
- src/hkdf.rs
- src/hmac.rs
- src/lib.rs
- src/options.rs
Contains all remaining improvements from #3.
> Audit improvements

- src/default.rs
- src/hkdf.rs
> Make HKDF fully RFC compliant

- src/hkdf.rs
- src/hmac.rs
- src/pbkdf2.rs
> Fix bug where the clear() function of the intended crate was not used

- src/hkdf.rs
- src/pbkdf2.rs
> Add compare for HKDF and PBKDF2

- src/hazardous/hash/blake2b.rs
- src/hazardous/mac/hmac.rs
- src/hazardous/mac/poly1305.rs
- src/hazardous/xof/cshake.rs
> Fix #46: Reset the state even if it hasn't been finalized yet

- src/auth.rs
- src/errors/mod.rs
- src/hazardous/hash/blake2b.rs
- src/hazardous/hash/sha512.rs
- src/hazardous/kdf/hkdf.rs
- src/hazardous/kdf/pbkdf2.rs
- src/hazardous/mac/hmac.rs
- src/hazardous/mac/poly1305.rs
- src/hazardous/xof/cshake.rs
- src/kdf.rs
- src/pwhash.rs
> Remove ValidationCryptoError and FinalizationCryptoError

- src/aead.rs
- src/hazardous/aead/chacha20poly1305.rs
- src/hazardous/aead/xchacha20poly1305.rs
- src/hazardous/hash/blake2b.rs
- src/hazardous/kdf/pbkdf2.rs
- src/hazardous/mac/hmac.rs
- src/hazardous/mac/poly1305.rs
- src/hazardous/stream/chacha20.rs
- src/hazardous/stream/xchacha20.rs
- src/hltypes.rs
- src/pwhash.rs
- src/typedefs.rs
- src/util/mod.rs
> Panic on CSPRNG error

- src/typedefs.rs
> Document PartialEq usage on two instances of the same newtype

- Cargo.toml
- README.md
- benches/bench.rs
This will allow benchmarking on stable Rust instead of only nightly.
> Switch to Criterion for benchmarks

- src/aead.rs
- src/auth.rs
- src/hash.rs
- src/hazardous/aead/chacha20poly1305.rs
- src/hazardous/aead/xchacha20poly1305.rs
- src/hazardous/hash/blake2b.rs
- src/hazardous/hash/sha512.rs
- src/hazardous/kdf/hkdf.rs
- src/hazardous/kdf/pbkdf2.rs
- src/hazardous/mac/hmac.rs
- src/hazardous/mac/poly1305.rs
- src/hazardous/stream/chacha20.rs
- src/hazardous/stream/xchacha20.rs
- src/kdf.rs
- src/lib.rs
- src/pwhash.rs
All of the hardcoded links to docs.rs have been removed. The documentation now works locally.
> Fix Issue #91 - Fix item links in docs

- .travis.yml
- README.md
> Test and document MSRV

- src/aead.rs
- src/hazardous/aead/chacha20poly1305.rs
- src/hazardous/aead/streaming.rs
- src/hazardous/aead/xchacha20poly1305.rs
Discussed in https://github.com/brycx/orion/pull/108.
> AEAD: Err instead of panic on input length addition overflow

- Cargo.toml
Fixes #148 
I removed the field of badges in Cargo.toml.
> Remove the badges from Cargo #148

- src/typedefs.rs
> Correct docs for typedefs with ct-comparison examples

- src/hazardous/kdf/hkdf.rs
- src/high_level/kdf.rs
- tests/kdf/mod.rs
> Remove hkdf::verify and orion::kdf::derive_key_verify()

- src/hazardous/aead/chacha20poly1305.rs
- src/hazardous/aead/streaming.rs
- src/hazardous/aead/xchacha20poly1305.rs
- src/hazardous/hash/blake2b.rs
- src/hazardous/hash/sha2/sha256.rs
- src/hazardous/hash/sha2/sha384.rs
- src/hazardous/hash/sha2/sha512.rs
- src/hazardous/kdf/argon2i.rs
- src/hazardous/kdf/hkdf.rs
- src/hazardous/kdf/pbkdf2.rs
- src/hazardous/mac/hmac.rs
- src/hazardous/mac/poly1305.rs
- src/hazardous/stream/chacha20.rs
- src/hazardous/stream/xchacha20.rs
- src/high_level/aead.rs
- src/high_level/auth.rs
- src/high_level/hash.rs
- src/high_level/hltypes.rs
- src/high_level/kdf.rs
- src/high_level/pwhash.rs
- src/lib.rs
- src/util/mod.rs
> Use intra-doc links and other small documentation improvements

- src/hazardous/kdf/argon2i.rs
- src/hazardous/kdf/pbkdf2.rs
> KDF output buffer zeroization documentation

- src/high_level/hltypes.rs
- src/high_level/kdf.rs
- src/high_level/pwhash.rs
> Add missing doc updates to `isize::MAX` length restrictions

- src/hazardous/ecc/x25519.rs
- src/typedefs.rs
> Add `serde` to `PublicKey`

- benches/bench.rs
> Add benchmarks for X25519

- README.md
fixes #215
Wiki page: https://github.com/orion-rs/orion/wiki/Crate-features
@vlmutolo could you see if this makes sense?
> New crate features wiki page

- src/hazardous/hash/sha2/mod.rs
- src/util/u64x4.rs
> Automatically derive `Default` for trivial cases

- src/hazardous/hash/blake2/blake2b.rs
This PR aims to solve this issue: https://github.com/orion-rs/orion/issues/278.
> derive debug and partialeq trait for blake2b hasher enum

- src/hazardous/kdf/pbkdf2.rs
It's some time since this was 100000. Update includes direct link to OWASP to more clearly indicate this should be checked before deciding.
> doc: Update PBKDF2 docs regarding iteration count

- CHANGELOG.md
- src/hazardous/hash/sha2/mod.rs
> sha2: Use `checked_mul(8)` instead of `checked_shl(3)`

- tests/mod.rs
> `clippy`: Remediate warning

- src/hazardous/kem/ml_kem/internal/mod.rs
closes #445 
This caches the encapsulation-key for the scope of a decapsulation key, avoiding the re-computation of matrix A in the decap_internal() routine.
> Cache encapsulation key for a decapsulation key

- src/test_framework/hpke_interface.rs
- src/test_framework/kem_interface.rs
> fix: typos in function

- src/hazardous/hash/sha3/mod.rs
- src/hazardous/kem/ml_kem/internal/sampling.rs
fixed some typos in code comments
> chore: fix typos

- src/typedefs.rs
missing word 'data' was added to comment
> chore: add missing word to comment
